In [1]:
%load_ext autoreload
%autoreload 1

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.data import Dataset

In [7]:
from denoiser import audio
path = 'D:\\Amit\\Documents\\ML Datasets\\Audio (Speech)\\Valentini\\clean_trainset_56spk_wav\\'
meta = audio.find_audio_files(path)
meta[:10]

KeyboardInterrupt: 

In [6]:
from denoiser.utils import LengthCalc
import numpy as np
calc = LengthCalc(5,8,4)
print(calc.first_greater(31))
print(calc.first_lower(np.array([0,2000,3000,5000])))

2388
[   0    0 2388 4436]


In [6]:
import os
os.path.join('path/to/data','**','*.wav')

'path/to/data\\**\\*.wav'

In [10]:
%aimport denoiser.audio
from denoiser import audio
path = 'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\'
meta = audio.find_audio_files(path)
meta

Loading audio metadata... Done! 


[('D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_001.wav',
  31367),
 ('D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_002.wav',
  52086),
 ('D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_003.wav',
  115715),
 ('D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_004.wav',
  77781),
 ('D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_005.wav',
  103896),
 ('D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_006.wav',
  81271)]

In [11]:
[audio.get_info(path) for path,length in meta]

[Info(length=31367, sample_rate=16000, channels=1),
 Info(length=52086, sample_rate=16000, channels=1),
 Info(length=115715, sample_rate=16000, channels=1),
 Info(length=77781, sample_rate=16000, channels=1),
 Info(length=103896, sample_rate=16000, channels=1),
 Info(length=81271, sample_rate=16000, channels=1)]

In [7]:
%aimport denoiser.data
from denoiser import data

In [8]:
path = 'D:\\Amit\\Documents\\GitHub\\denoiser\\egs\\debug\\tr\\'
files_ds = data.load_files(path)
list(files_ds.as_numpy_iterator())

[(b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\noisy\\p287_001.wav',
  b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_001.wav'),
 (b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\noisy\\p287_002.wav',
  b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_002.wav'),
 (b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\noisy\\p287_003.wav',
  b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_003.wav'),
 (b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\noisy\\p287_004.wav',
  b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_004.wav'),
 (b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\noisy\\p287_005.wav',
  b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_005.wav'),
 (b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\noisy\\p287_006.wav',
  b'D:\\Amit\\Documents\\GitHub\\denoiser\\dataset\\debug\\clean\\p287_006.wav')]

In [9]:
audio_ds = data.generate_audio(files_ds)
audio = list(audio_ds.as_numpy_iterator())
[(a.shape,b.shape) for a,b in audio]

[((31367, 1), (31367, 1)),
 ((52086, 1), (52086, 1)),
 ((115715, 1), (115715, 1)),
 ((77781, 1), (77781, 1)),
 ((103896, 1), (103896, 1)),
 ((81271, 1), (81271, 1))]

In [85]:
from IPython.display import Audio
import numpy as np
Audio(audio[0][0].reshape((1,-1)), rate=16000)

In [69]:
def unzip(dataset):
    return tuple(
        dataset.map(lambda *x: x[i])
        for i in range(len(dataset.element_spec)))

In [83]:
noisy_ds, clean_ds = unzip(files_ds)
noisy_audio_ds = data.generate_audio(noisy_ds)
[x.shape for x in noisy_audio_ds.as_numpy_iterator()]

[(31367, 1), (52086, 1), (115715, 1), (77781, 1), (103896, 1), (81271, 1)]

In [9]:
examples_ds = data.generate_examples(audio_ds, length=16000*2, stride=16000//2)
[(a.shape,b.shape) for a,b in examples_ds.as_numpy_iterator()]

[((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1)),
 ((32000, 1), (32000, 1))]

In [113]:
noisy_ex, clean_ex = [(a,b) for a,b in examples_ds.as_numpy_iterator()][9]
Audio(noisy_ex.reshape((1,-1)), rate=16000)

In [114]:
Audio(clean_ex.reshape((1,-1)), rate=16000)

In [7]:
samples_ds = data.generate_samples(audio_ds)
[((a[0].shape,a[1]),(b[0].shape,b[1])) for a,b in samples_ds.as_numpy_iterator()]

[(((31367, 1), 31367), ((31367, 1), 31367)),
 (((52086, 1), 52086), ((52086, 1), 52086)),
 (((115715, 1), 115715), ((115715, 1), 115715)),
 (((77781, 1), 77781), ((77781, 1), 77781)),
 (((103896, 1), 103896), ((103896, 1), 103896)),
 (((81271, 1), 81271), ((81271, 1), 81271))]

In [8]:
samples_ds = data.generate_samples(audio_ds, batch=3)
[((a[0].shape,a[1]),(b[0].shape,b[1])) for a,b in samples_ds.as_numpy_iterator()]

[(((3, 115715, 1), array([ 31367,  52086, 115715])),
  ((3, 115715, 1), array([ 31367,  52086, 115715]))),
 (((3, 103896, 1), array([ 77781, 103896,  81271])),
  ((3, 103896, 1), array([ 77781, 103896,  81271])))]

In [137]:
def convert(elem):
        try: return elem.shape
        except:
            if isinstance(elem, list):
                return to_shapes(elem)
            elif isinstance(elem, tuple):
                return tuple(to_shapes(elem))
            else: return elem
def to_shapes(lst):
    return [convert(elem) for elem in lst]

In [147]:
combined_ds = Dataset.zip((examples_ds, samples_ds.repeat()))
to_shapes(combined_ds.as_numpy_iterator())

[(((8000, 1), (8000, 1)), (((3, 115715, 1), (3,)), ((3, 115715, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 103896, 1), (3,)), ((3, 103896, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 115715, 1), (3,)), ((3, 115715, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 103896, 1), (3,)), ((3, 103896, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 115715, 1), (3,)), ((3, 115715, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 103896, 1), (3,)), ((3, 103896, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 115715, 1), (3,)), ((3, 115715, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 103896, 1), (3,)), ((3, 103896, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 115715, 1), (3,)), ((3, 115715, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 103896, 1), (3,)), ((3, 103896, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 115715, 1), (3,)), ((3, 115715, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 103896, 1), (3,)), ((3, 103896, 1), (3,)))),
 (((8000, 1), (8000, 1)), (((3, 115715, 1), (3,)), ((3, 115715, 1), (3,)))),

In [155]:
max_steps = 3
batch_size = 10

# create the appropriate indices here
indices = (tf.range(max_steps) +
    tf.range(batch_size)[:,np.newaxis])[...,np.newaxis]
indices

<tf.Tensor: shape=(10, 3, 1), dtype=int32, numpy=
array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]]])>

In [160]:
length=5
stride=3
indices = tf.range(length)+tf.range(0,20-length+1,stride)[:,np.newaxis]
indices

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 3,  4,  5,  6,  7],
       [ 6,  7,  8,  9, 10],
       [ 9, 10, 11, 12, 13],
       [12, 13, 14, 15, 16],
       [15, 16, 17, 18, 19]])>

In [168]:
x = np.random.randint(100,size=(20,1))
print(x)
tf.gather_nd(x, indices[...,np.newaxis])

[[61]
 [55]
 [32]
 [35]
 [30]
 [10]
 [92]
 [48]
 [86]
 [28]
 [48]
 [43]
 [29]
 [46]
 [69]
 [88]
 [30]
 [10]
 [13]
 [78]]


<tf.Tensor: shape=(6, 5, 1), dtype=int32, numpy=
array([[[61],
        [55],
        [32],
        [35],
        [30]],

       [[35],
        [30],
        [10],
        [92],
        [48]],

       [[92],
        [48],
        [86],
        [28],
        [48]],

       [[28],
        [48],
        [43],
        [29],
        [46]],

       [[29],
        [46],
        [69],
        [88],
        [30]],

       [[88],
        [30],
        [10],
        [13],
        [78]]])>

In [179]:
func_examples = lambda audio: data.extract_examples_static(audio, 16000*2, 16000//2)
func_sample = lambda t: (t,tf.shape(t)[0])
combined_ds = audio_ds.map(data.apply(lambda audio: (func_examples(audio), func_sample(audio))))
combined_ds.element_spec

((TensorSpec(shape=(None, 32000, None), dtype=tf.float32, name=None),
  (TensorSpec(shape=(None, None), dtype=tf.float32, name=None),
   TensorSpec(shape=(), dtype=tf.int32, name=None))),
 (TensorSpec(shape=(None, 32000, None), dtype=tf.float32, name=None),
  (TensorSpec(shape=(None, None), dtype=tf.float32, name=None),
   TensorSpec(shape=(), dtype=tf.int32, name=None))))

In [180]:
to_shapes(combined_ds.as_numpy_iterator())

[(((0, 32000, 1), ((31367, 1), ())), ((0, 32000, 1), ((31367, 1), ()))),
 (((3, 32000, 1), ((52086, 1), ())), ((3, 32000, 1), ((52086, 1), ()))),
 (((11, 32000, 1), ((115715, 1), ())), ((11, 32000, 1), ((115715, 1), ()))),
 (((6, 32000, 1), ((77781, 1), ())), ((6, 32000, 1), ((77781, 1), ()))),
 (((9, 32000, 1), ((103896, 1), ())), ((9, 32000, 1), ((103896, 1), ()))),
 (((7, 32000, 1), ((81271, 1), ())), ((7, 32000, 1), ((81271, 1), ())))]

In [182]:
batched_ds = combined_ds.padded_batch(3)
to_shapes(batched_ds.as_numpy_iterator())

[(((3, 11, 32000, 1), ((3, 115715, 1), (3,))),
  ((3, 11, 32000, 1), ((3, 115715, 1), (3,)))),
 (((3, 9, 32000, 1), ((3, 103896, 1), (3,))),
  ((3, 9, 32000, 1), ((3, 103896, 1), (3,))))]

In [194]:
ds = data.generate_dataset(files_ds, 16000*2, 16000//2, batch=3)
to_shapes(ds.as_numpy_iterator())

[(((33, 32000, 1), ((3, 115715, 1), (3,))),
  ((33, 32000, 1), ((3, 115715, 1), (3,)))),
 (((27, 32000, 1), ((3, 103896, 1), (3,))),
  ((27, 32000, 1), ((3, 103896, 1), (3,))))]